---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - ./rubocop/bridgetown

Bridgetown/NoPutsAllowed:
  Exclude:
    - rake/*.rake

AllCops:
  TargetRubyVersion: 2.4
  Include:
    - lib/**/*.rb
    - test/**/*.rb
  Exclude:
    - bin/**/*
    - exe/**/*
    - benchmark/**/*
    - script/**/*
    - vendor/**/*
    - tmp/**/*
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
Layout/IndentationWidth:
  Severity: error
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Lint/NestedPercentLiteral:
  Exclude:
    - test/test_site.rb
Layout/EmptyComment:
  Enabled: false
Layout/EndAlignment:
  Severity: error
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/UnreachableCode:
  Severity: error
Lint/Void:
  Exclude:
    - lib/bridgetown/site.rb
Metrics/AbcSize:
  Max: 21
Metrics/BlockLength:
  Exclude:
    - test/**/*.rb
    - lib/bridgetown/configuration.rb
    - rake/*.rake
Metrics/ClassLength:
  Exclude:
    - !ruby/regexp /features\/.*.rb$/
    - !ruby/regexp /test\/.*.rb$/
    - lib/bridgetown/document.rb
    - lib/bridgetown/site.rb
    - lib/bridgetown/commands/serve.rb
    - lib/bridgetown/configuration.rb
  Max: 240
Metrics/CyclomaticComplexity:
  Exclude:
    - lib/bridgetown/utils.rb
    - lib/bridgetown/commands/serve.rb
Layout/LineLength:
  Exclude:
    - !ruby/regexp /features\/.*.rb/
    - Rakefile
    - rake/*.rake
    - Gemfile
  Max: 100
  Severity: warning
Metrics/MethodLength:
  CountComments: false
  Max: 20
  Severity: error
Metrics/ModuleLength:
  Max: 240
  Exclude:
    - lib/bridgetown/filters.rb
Metrics/ParameterLists:
  Max: 4
Metrics/PerceivedComplexity:
  Max: 8
Naming/FileName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Exclude:
    - test/**/*.rb
Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/bridgetown/convertible.rb
    - lib/bridgetown/drops/site_drop.rb
    - lib/bridgetown/drops/unified_payload_drop.rb
    - lib/bridgetown/page_without_a_file.rb
Security/MarshalLoad:
  Exclude:
    - !ruby/regexp /test\/.*.rb$/
    - lib/bridgetown/regenerator.rb
Security/YAMLLoad:
  Exclude:
    - !ruby/regexp /features\/.*.rb/
    - !ruby/regexp /test\/.*.rb$/
Style/AccessModifierDeclarations:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/AndOr:
  Severity: error
Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FormatStringToken:
  Exclude:
    - lib/bridgetown/utils/ansi.rb
    - lib/bridgetown/liquid_renderer/table.rb
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Severity: error
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: true
Style/MixinUsage:
  Exclude:
    - test/helper.rb
Style/ModuleFunction:
  Enabled: false
Style/MultilineTernaryOperator:
  Severity: error
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%q": "{}"
    "%Q": "{}"
    "%r": "!!"
    "%s": "()"
    "%w": "()"
    "%W": "()"
    "%x": "()"
Style/RegexpLiteral:
  EnforcedStyle: percent_r
Style/RescueModifier:
  Enabled: false
Style/SafeNavigation:
  Exclude:
    - lib/bridgetown/document.rb
Style/SignalException:
  EnforcedStyle: only_raise
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
